apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis
  template:
    metadata:
      labels:
        app: auth-redis
    spec:
      containers:
        - name: auth-redis
          image: bitnami/redis:latest
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-srv
spec:
  selector:
    app: auth-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379