apiVersion: apps/v1
kind: Deployment
metadata:
  name: spectacles-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spectacles-mongo
  template:
    metadata:
      labels:
        app: spectacles-mongo
    spec:
      containers:
        - name: spectacles-mongo
          image: mongo
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: spectacles-init
---
apiVersion: v1
kind: Service
metadata:
  name: spectacles-mongo-srv
spec:
  selector:
    app: spectacles-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spectacles-init
data:
  spectacles-init.js: |-
    db = db.getSiblingDB("spectacles");
    db.screeningrooms.insertMany([
        {
            roomNumber: 1,
            name: "normal_room",
            rows: {
                "1": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "2": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "3": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "4": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "5": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "6": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "7": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "8": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "9": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
                "10": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
            },
            passages: [6, 16],
        },
        {
            roomNumber: 2,
            name: "vip_room",
            rows: {
                "1": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
                "2": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
                "3": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
                "4": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
                "5": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
                "6": { "seats": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"] },
            },
            passages: [7],
        },
    ])
